### ISSUE TITLE
アイテム検知と寝てない人検知

### ISSUE THREAD

**Issue by nagasaki7110** [tutinoko2048/TNAntiCheat#13]
特定のアイテムを持った人を検知することをconfig.jsに追加することは可能なのでしょう？
持つをkickではなくて持つを検知です
例えば魚類が入っているバケツは禁止にしてキックまではしたくないけどたくないけど念のため持った人を検知して表示できるようにです

又夜になって寝てない人（playanimationコマンドを利用して）を検知するアドオンを作ることは可能なのでしょうか？

よろしくお願い致します

**Comment by nagasaki7110** [comment]
逆に寝た人検知だけでも大丈夫です　現状だと最初に寝た人しか表示されないです

**Comment by tutinoko2048** [comment]
禁止アイテムを持ったらアイテムだけ消す ということならできます
寝ていない人検知はplayanimationは分かりませんがanimation_controllersを使えば出来ると思います

**Comment by nagasaki7110** [comment]
githubの使い方も詳しくなくてここに書き込んでいいか迷いましたが返答頂きありがとうございます！
アドオン作ったことなくてコマンドもそんなに詳しくないのですが自分で追加又は作れないか勉強してみます
お忙しいことと思うので無理かもしれませんが将来追加又は作る検討していただけると有難いです
寝てない人（又は寝てる人）検知は一部の参加型配信でしか需要ないのかもしれませんが。
なおこの#13は不要でしたら削除（クローズ？）して頂いても大丈夫です
一部の参加型配信でこのアンチチートアドオン役に立っているのでこれからもバージョンアップがんばってください！
それとここで聞く事ではないのかもしれませんが"op": "ac:admin", // 検知から除外するタグです
のac:adminの部分を自分のゲーマータグに書き換えても除外できませんでした
他にも書き方いろいろ試したのですがわかりませんでした　もしよろしければ書き方教えて頂くことはできますか？
よろしくお願い致します

**Comment by tutinoko2048** [comment]
ac:adminはタグ名なので /tag @s add ac:admin ってコマンドを実行していただければ除外できますよ〜

**Comment by nagasaki7110** [comment]
なるほどです！助かりました
教えて頂き本当にありがとうございます
