### ISSUE TITLE
NBT editing

### ISSUE THREAD

**Issue by JKearnsl** [tutinoko2048/TNAntiCheat#27]
As you already know, you can change the nbt of things and at the moment the anti-cheat allows this.

Regular item name changes or adding enchantments do not have critical consequences, but anti-cheat allows changing/adding such critical nbt properties as "may break"/"may deliver", which entails huge consequences.

Let this topic be open until a solution is found.

**Comment by tutinoko2048** [comment]
Could you please tell me which features of the anti-cheat may change critical NBT properties?

**Comment by JKearnsl** [comment]
> Could you please tell me which features of the anti-cheat may change critical NBT properties?

None. Here you need to solve the issue from the other side: you need to catch changes in the subject from the client side.

As I noticed, you caught template nbts, such as shulkerbox with items. If you solve the problem on a large scale, then all this will become unnecessary and clear the anti-cheat.

**Comment by JKearnsl** [comment]
I have not studied the gametest framework. I don't write anything in js. You need to solve this problem yourself
If it turns out that gametest can't catch client-side changes to the item, then we'll have to wait for that in the future.
